# Generated by Django 5.2.7 on 2025-10-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_centers_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
