# Generated by Django 5.2.7 on 2025-10-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Centers',
            new_name='Center',
        ),
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ['name'], 'verbose_name': 'Молодежный центр', 'verbose_name_plural': 'Молодежные центры'},
        ),
    ]
