# Generated by Django 5.2.7 on 2025-10-09 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rename_centers_center_alter_center_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='center',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='organization.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='center',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to='centers/emblems/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='center',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
