# Generated by Django 5.2.7 on 2025-10-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_center_address_alter_center_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
    ]
