# Generated by Django 5.2.7 on 2025-10-09 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_center_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center', to='organization.district', verbose_name='Район'),
        ),
    ]
