# Generated by Django 5.2.7 on 2025-10-09 10:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.IntegerField(blank=True, help_text='ID пользователя в Телеграмме. Заполняется если пользователь должен получать уведомление через Телеграмм (после того как его сделают ответственным за помещение).', null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
