# Generated by Django 5.2.7 on 2025-10-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_groupproxy_alter_customuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Этот номер увидят те, кто бронирют помещения', max_length=15, null=True, verbose_name='Номер телефона'),
        ),
    ]
