# Generated by Django 5.2.7 on 2025-10-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Этот номер увидят те, кто бронируют помещения', max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='ID пользователя в Телеграмме. Заполняется если пользователь должен получать уведомление через Телеграмм (после того как его сделают ответственным за помещение).', max_length=50, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
