version: "3.9"
services:
  database:
    image: postgres:15-alpine
    volumes:
      - psg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: minmol_db
      POSTGRES_USER: minmol_user
      POSTGRES_PASSWORD: minmol_password
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  psg_data:
