# Generated by Django 5.2.7 on 2025-10-09 18:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('CANCELED', 'Отменено')], default='PENDING', help_text='Для одобрения или отклонения запроса на бронирование необходимо отредактировать этот пункт', max_length=10, verbose_name='Текущий статус бронирования')),
                ('rejection_reason', models.TextField(blank=True, help_text='При отклонении обязательно необходимо заполнить причину отклонения', verbose_name='Причина отклонения')),
                ('start_at', models.DateTimeField(help_text='Дата и время начала бронирования', verbose_name='Начало бронирования')),
                ('end_at', models.DateTimeField(help_text='Дата и время окончания бронирования', verbose_name='Окончание бронирования')),
                ('applicant_name', models.CharField(max_length=255, verbose_name='Имя заявителя')),
                ('applicant_tg_username', models.CharField(max_length=255, verbose_name='Имя заявителя в Telegram')),
                ('applicant_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Введите телефон в формате +79991234567', regex='^\\+?\\d{10,15}$')], verbose_name='Номер телефона заявителя')),
                ('event_name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('event_purpose', models.CharField(max_length=255, verbose_name='Цель мероприятия')),
                ('target_audience', models.CharField(max_length=255, verbose_name='Целевая аудитория')),
                ('invited_speakers', models.CharField(max_length=255, verbose_name='Приглашенные спикеры')),
                ('required_equipment', models.CharField(max_length=255, verbose_name='Список необходимого оборудования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Вмещаемость')),
                ('image', models.ImageField(blank=True, help_text='Возможно добавить только одно изображение', null=True, upload_to='rooms/images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='RoomTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Тег помещения',
                'verbose_name_plural': 'Теги помещений',
                'ordering': ['name'],
            },
        ),
    ]
