# Generated by Django 5.2.7 on 2025-10-09 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Вмещаемость'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Возможно добавить только одно изображение', null=True, upload_to='rooms/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='room',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='ФИО и номер телефона данного сотрудника увидят внешние пользователи Telegram(если заполнен). Если у сотрудника заполнен Telegram ID, то он получит уведомление при поступлении заявки бронирования.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Ответсвенный за помещение'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='booking.roomtag', verbose_name='Теги помещении'),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='roomtag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
