# Generated by Django 5.2.7 on 2025-10-10 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='ФИО и номер телефона данного сотрудника увидят внешние пользователи Telegram(если заполнен). Если у сотрудника заполнен Telegram ID, то он получит уведомление при поступлении заявки бронирования.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Ответсвенный за помещение'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.room', verbose_name='Помещение'),
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='booking.roomtag', verbose_name='Теги помещении'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REJECTED'), _negated=True), models.Q(('rejection_reason', ''), _negated=True), _connector='OR'), name='booking_rejection_reason_required_on_rejected'),
        ),
    ]
