# Generated by Django 5.2.7 on 2025-10-10 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Если у сотрудника заполнен Telegram ID, то он получит уведомление при поступлении заявки бронирования.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Ответсвенный за помещение'),
        ),
    ]
