# Generated by Django 5.2.7 on 2025-10-09 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='center',
            field=models.ForeignKey(blank=True, help_text='Какому Молодежному центру принадлежит это помещение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_for_rooms', to='organization.center', verbose_name='Молодежный центр'),
        ),
    ]
