# Generated by Django 5.2.7 on 2025-10-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Указывает, следует ли считать это помещение активным. Можно снять это выделение вместо удаления, тогда пользователи не увидят помещение в Telegram', verbose_name='Активное помещение'),
        ),
    ]
