# Generated by Django 5.2.7 on 2025-10-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_room_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='applicant_tg_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Telegram ID заявителя'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='applicant_tg_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram username заявителя'),
        ),
    ]
